var PBANKLOGINMENUINFO = {
    "rspHead": {
        "acctDate": "",
        "tranTime": "165414",
        "channelDate": "20160906",
        "langCode": "",
        "returnCode": "00000000",
        "tranDate": "20160906",
        "globalSeqNo": "000120160906222200000001174001",
        "returnMsg": "交易成功",
        "rsrvContent": "",
        "backendSysId": "2222",
        "backendSeqNo": "0001201609062222000000011740019001000000"
    },
    "rspBody": {
        "returnList": {
            "itemValue": null,
            "children": [
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 1,
                        "bmfName": "首页",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "302001001",
                        "bmfCode": "302001001",
                        "bmfUrl": "index",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "首页",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": []
                },
                {
                    "itemValue": {
                        "bmf_note2": "",
                        "bmfProperties": "Y",
                        "bmprMenucode": "302001002",
                        "bmf_note1": "",
                        "parentShelf": "",
                        "bmfLevel": "1",
                        "bmfChannel": "2222",
                        "bmfSeqno": 2,
                        "bmfName": "账户管理",
                        "bmfStt": "0",
                        "shelfDesc": "账户管理描述",
                        "bmfId": "302001002",
                        "bmfCode": "302001002",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "账户",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "账户",
                        "bmprShelfcode": "SD01",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": "1"
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 8,
                                "bmfName": "我的账户",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "01306dd2-3c43-439a-9860-d25d40bec731",
                                "bmfCode": "302001049",
                                "bmfUrl": "accountManagement",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001002",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 9,
                                "bmfName": "账户设置",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "90337ac1-305d-44af-9fbb-ba4824fc51aa",
                                "bmfCode": "302001029",
                                "bmfUrl": "setAccount",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001002",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 10,
                                "bmfName": "交易明细",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "5335c09d-b149-4ead-9f9b-82c288254cb0",
                                "bmfCode": "302001030",
                                "bmfUrl": "accountDetail",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001002",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 11,
                                "bmfName": "账户挂失",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "b6a46b7e-fbeb-4bc2-9ee7-11a498a6a0fd",
                                "bmfCode": "302001031",
                                "bmfUrl": "suspendAccount",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001002",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmf_note2": "",
                        "bmfProperties": "Y",
                        "bmprMenucode": "302001003",
                        "bmf_note1": "",
                        "parentShelf": "",
                        "bmfLevel": "1",
                        "bmfChannel": "2222",
                        "bmfSeqno": 3,
                        "bmfName": "投资理财",
                        "bmfStt": "0",
                        "shelfDesc": "理财管理描述",
                        "bmfId": "302001003",
                        "bmfCode": "302001003",
                        "bmfUrl": "consumerFinancial",
                        "bmprPrdtypecode": "",
                        "shelfName": "理财",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "理财",
                        "bmprShelfcode": "SD02",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": "2"
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "我的理财产品",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "c2f0d313-aa9f-4671-aff0-e343cf7c8511",
                                "bmfCode": "302001057",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001003",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "交易明细查询",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "af5d38ce-3c61-48e7-bcd3-50ad7b1046ca",
                                "bmfCode": "302001058",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001003",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 3,
                                "bmfName": "理财产品购买",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "8abaf229-faec-4a2b-a0a2-45983a0ceea9",
                                "bmfCode": "302001059",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001003",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 4,
                                "bmfName": "理财产品撤单",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "d524b8b3-b0c1-4818-870e-3b94a330fc10",
                                "bmfCode": "302001060",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001003",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 5,
                                "bmfName": "风险承受能力评估",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "a488662a-56ad-4ebb-8c95-48bbf8589c01",
                                "bmfCode": "302001061",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "302001003",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmf_note2": "",
                        "bmfProperties": "Y",
                        "bmprMenucode": "302001004",
                        "bmf_note1": "",
                        "parentShelf": "",
                        "bmfLevel": "1",
                        "bmfChannel": "2222",
                        "bmfSeqno": 4,
                        "bmfName": "贷款产品",
                        "bmfStt": "0",
                        "shelfDesc": "贷款产品管理描述",
                        "bmfId": "302001004",
                        "bmfCode": "302001004",
                        "bmfUrl": "loanService",
                        "bmprPrdtypecode": "",
                        "shelfName": "贷款产品",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "贷款产品",
                        "bmprShelfcode": "SD07",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": "7"
                    },
                    "children": []
                },
                {
                    "itemValue": {
                        "bmf_note2": "",
                        "bmfProperties": "Y",
                        "bmprMenucode": "302001005",
                        "bmf_note1": "",
                        "parentShelf": "",
                        "bmfLevel": "1",
                        "bmfChannel": "2222",
                        "bmfSeqno": 5,
                        "bmfName": "定活宝",
                        "bmfStt": "0",
                        "shelfDesc": "定活宝管理描述",
                        "bmfId": "302001005",
                        "bmfCode": "302001005",
                        "bmfUrl": "transferService",
                        "bmprPrdtypecode": "",
                        "shelfName": "定活宝",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "定活宝",
                        "bmprShelfcode": "SD03",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": "3"
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmf_note2": "",
                                "bmfProperties": "Y",
                                "bmprMenucode": "302001025",
                                "bmf_note1": "",
                                "parentShelf": "SD03",
                                "bmfLevel": "2",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "定期产品分类",
                                "bmfStt": "0",
                                "shelfDesc": "定期存款分类",
                                "bmfId": "302001025",
                                "bmfCode": "302001025",
                                "bmfUrl": "transferService",
                                "bmprPrdtypecode": "",
                                "shelfName": "定期存款分类2",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "定期产品分类",
                                "bmprShelfcode": "SD0301",
                                "bmfParentid": "302001005",
                                "bmprGoodscode": "",
                                "bmprId": "21"
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmf_note2": "",
                                "bmfProperties": "Y",
                                "bmprMenucode": "302001026",
                                "bmf_note1": "",
                                "parentShelf": "SD03",
                                "bmfLevel": "2",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "活期产品分类",
                                "bmfStt": "0",
                                "shelfDesc": "活期存款分类12",
                                "bmfId": "302001026",
                                "bmfCode": "302001026",
                                "bmfUrl": "transferService",
                                "bmprPrdtypecode": "",
                                "shelfName": "活期存款分类12",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "活期产品分类",
                                "bmprShelfcode": "SD0302",
                                "bmfParentid": "302001005",
                                "bmprGoodscode": "",
                                "bmprId": "22"
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmf_note2": "",
                        "bmfProperties": "Y",
                        "bmprMenucode": "302001006",
                        "bmf_note1": "",
                        "parentShelf": "",
                        "bmfLevel": "1",
                        "bmfChannel": "2222",
                        "bmfSeqno": 6,
                        "bmfName": "存款产品",
                        "bmfStt": "0",
                        "shelfDesc": "存款产品管理描述",
                        "bmfId": "302001006",
                        "bmfCode": "302001006",
                        "bmfUrl": "localhost:8080/账户",
                        "bmprPrdtypecode": "",
                        "shelfName": "存款产品",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "存款产品",
                        "bmprShelfcode": "SD04",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": "4"
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmf_note2": "",
                                "bmfProperties": "Y",
                                "bmprMenucode": "302001007",
                                "bmf_note1": "",
                                "parentShelf": "SD04",
                                "bmfLevel": "1",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "存款分类",
                                "bmfStt": "0",
                                "shelfDesc": "存款分类描述",
                                "bmfId": "302001007",
                                "bmfCode": "302001007",
                                "bmfUrl": "localhost:8080/账户",
                                "bmprPrdtypecode": "",
                                "shelfName": "存款分类",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "存款分类",
                                "bmprShelfcode": "SD0401",
                                "bmfParentid": "302001006",
                                "bmprGoodscode": "",
                                "bmprId": "5"
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmf_note2": "",
                                "bmfProperties": "Y",
                                "bmprMenucode": "302001008",
                                "bmf_note1": "",
                                "parentShelf": "SD04",
                                "bmfLevel": "2",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "借记卡分类",
                                "bmfStt": "0",
                                "shelfDesc": "借记卡分类描述",
                                "bmfId": "302001008",
                                "bmfCode": "302001008",
                                "bmfUrl": "localhost:8080/账户",
                                "bmprPrdtypecode": "",
                                "shelfName": "借记卡分类",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "借记卡分类",
                                "bmprShelfcode": "SD0402",
                                "bmfParentid": "302001006",
                                "bmprGoodscode": "",
                                "bmprId": "6"
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 7,
                        "bmfName": "转账汇款",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                        "bmfCode": "302001032",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "行内转账",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "2c01e8a4-f484-421a-8d99-23b0e61fb43b",
                                "bmfCode": "302001050",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "本行汇款",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "8b043a43-cd2c-46ae-aba4-40cd0a52a1a7",
                                        "bmfCode": "302001051",
                                        "bmfUrl": "bankTransfer",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "2c01e8a4-f484-421a-8d99-23b0e61fb43b",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "同名转账",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "0d119dec-2bcd-4df4-9f76-9a60400c4468",
                                        "bmfCode": "302001052",
                                        "bmfUrl": "sameNameTransfer",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "2c01e8a4-f484-421a-8d99-23b0e61fb43b",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 3,
                                        "bmfName": "行内转账历史",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "66b44cd5-0104-481a-887f-e57c7ce934bc",
                                        "bmfCode": "302001053",
                                        "bmfUrl": "bankTransferDetail",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "2c01e8a4-f484-421a-8d99-23b0e61fb43b",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "跨行汇款",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "0a509f91-1e7f-4ffb-8fcd-c4fe8eaf7573",
                                "bmfCode": "302001054",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "跨行汇款",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "210d83ee-7840-401a-980a-2f0eb9a94280",
                                        "bmfCode": "302001055",
                                        "bmfUrl": "interBankTransfer",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "0a509f91-1e7f-4ffb-8fcd-c4fe8eaf7573",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "跨行转账历史",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "f7cf46ad-7819-463e-a850-8bcac48dad83",
                                        "bmfCode": "302001056",
                                        "bmfUrl": "interBankTransferDetail",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "0a509f91-1e7f-4ffb-8fcd-c4fe8eaf7573",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 3,
                                "bmfName": "收款人维护",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "49472e71-a92e-4431-b7c2-fa4bac9ad287",
                                "bmfCode": "302001034",
                                "bmfUrl": "recvPersonInfo",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 4,
                                "bmfName": "回单打印",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "a5efa36b-9c9d-48fc-bb5e-18d104c31a88",
                                "bmfCode": "302001033",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "电子回单打印",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "19e3db13-3e4c-478e-9c8e-7e44739b6267",
                                        "bmfCode": "302001036",
                                        "bmfUrl": "elecReceiptPrint",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "a5efa36b-9c9d-48fc-bb5e-18d104c31a88",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "电子回单验证",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "f6582be5-7d24-4714-b8d8-bdd09dabfbc7",
                                        "bmfCode": "302001037",
                                        "bmfUrl": "elecReceiptCheck",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "a5efa36b-9c9d-48fc-bb5e-18d104c31a88",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 5,
                                "bmfName": "落地审批查询",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "252c928a-f349-4b0b-a91a-53ce81dc054e",
                                "bmfCode": "302001035",
                                "bmfUrl": "floorApproval",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "d12bf60e-a7a4-4d8e-9996-9cf5f654a161",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 8,
                        "bmfName": "网银互联",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "7dc83e63-5bfc-4b99-ad45-7e00baf23cca",
                        "bmfCode": "302001038",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "网银互联管理",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "753b5470-d9a4-4b87-87e2-1471a39dc9cc",
                                "bmfCode": "302001039",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "7dc83e63-5bfc-4b99-ad45-7e00baf23cca",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "签约他行账户",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "2cda315e-b4e8-4ea8-9b72-b9d79d03b7c4",
                                        "bmfCode": "302001040",
                                        "bmfUrl": "signedHeDid",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "753b5470-d9a4-4b87-87e2-1471a39dc9cc",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "签约协议管理",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "380d9a21-db27-484c-b793-ce2ce6a63469",
                                        "bmfCode": "302001041",
                                        "bmfUrl": "contractManage",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "753b5470-d9a4-4b87-87e2-1471a39dc9cc",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 3,
                                        "bmfName": "他行账户管理",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "27d6a9af-e375-4685-a39f-fd721f4a3dab",
                                        "bmfCode": "302001042",
                                        "bmfUrl": "heDidmanage",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "753b5470-d9a4-4b87-87e2-1471a39dc9cc",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "账户资金归集",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "a3e71ee9-9dde-434f-be29-dddd65eedbf2",
                                "bmfCode": "302001043",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "7dc83e63-5bfc-4b99-ad45-7e00baf23cca",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "资金归集设置",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "859943a5-0a05-479a-9cf2-8e342f942d8a",
                                        "bmfCode": "302001044",
                                        "bmfUrl": "setFundCollection",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "a3e71ee9-9dde-434f-be29-dddd65eedbf2",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "跨行汇入",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "c5013feb-5830-459c-a960-7e7920b481f9",
                                        "bmfCode": "302001045",
                                        "bmfUrl": "interBank",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "a3e71ee9-9dde-434f-be29-dddd65eedbf2",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 3,
                                        "bmfName": "资金归集管理",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "2d31f46d-61f1-4c57-82b9-eca52ffec7e2",
                                        "bmfCode": "302001046",
                                        "bmfUrl": "funcollmanag",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "a3e71ee9-9dde-434f-be29-dddd65eedbf2",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 9,
                        "bmfName": "个人中心",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                        "bmfCode": "302001047",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "个人限额维护",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "6dac0fe5-e7a2-4e6b-8a04-ed47fb6d185d",
                                "bmfCode": "302001048",
                                "bmfUrl": "personallimit",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "操作日志查询",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "47a182c4-b1a5-459e-a038-c917f5bf4890",
                                "bmfCode": "302001079",
                                "bmfUrl": "operationquery",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 3,
                                "bmfName": "客户昵称设置",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "6b30d66c-da4d-4527-a353-6c2411d0560f",
                                "bmfCode": "302001080",
                                "bmfUrl": "customernickname",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 4,
                                "bmfName": "预留信息设置",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "d8c4be11-325d-4efe-b45f-4f8ce4032f27",
                                "bmfCode": "302001081",
                                "bmfUrl": "reservedinformation",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 5,
                                "bmfName": "修改登录密码",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "b894d5c1-7787-4a4a-81e7-69d1f7540c49",
                                "bmfCode": "302001082",
                                "bmfUrl": "modifypassword",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 6,
                                "bmfName": "快捷菜单设置",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "f8de8c1c-a5c9-4e3a-aacd-f496fb424f56",
                                "bmfCode": "302001083",
                                "bmfUrl": "shortcutmenusettings",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 7,
                                "bmfName": "电子渠道管理",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "f612a391-b496-44c9-96f0-6965ce753ccc",
                                "bmfCode": "302001084",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "9f02cbfc-96e7-4095-9c3f-b27f71b0414a",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 10,
                        "bmfName": "储蓄服务",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "445c42c5-8e72-4b7c-aeb7-7f3fd32aa129",
                        "bmfCode": "302001062",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "定活互转",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "77f16ea8-323c-4569-9288-0cabed50a89e",
                                "bmfCode": "302001065",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "445c42c5-8e72-4b7c-aeb7-7f3fd32aa129",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "定期转活期",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "221a395a-2e47-44a5-8c4c-56c7f86aa20c",
                                        "bmfCode": "302001067",
                                        "bmfUrl": "timeToCurrentDeposit",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "77f16ea8-323c-4569-9288-0cabed50a89e",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "活期转定期",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "fb8cf310-0535-4f7e-a118-42e6ba71cbe6",
                                        "bmfCode": "302001068",
                                        "bmfUrl": "currentToTimeDeposit",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "77f16ea8-323c-4569-9288-0cabed50a89e",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "通知存款",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "789206f1-6db5-4dce-97c9-e9263addf209",
                                "bmfCode": "302001066",
                                "bmfUrl": "",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "445c42c5-8e72-4b7c-aeb7-7f3fd32aa129",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": [
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 1,
                                        "bmfName": "我的通知存款",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "81dcd1b4-4530-46f9-8883-48f6f67cf70f",
                                        "bmfCode": "302001069",
                                        "bmfUrl": "myNoticeDeposit",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "789206f1-6db5-4dce-97c9-e9263addf209",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                },
                                {
                                    "itemValue": {
                                        "bmfProperties": "N",
                                        "bmprMenucode": "",
                                        "parentShelf": "",
                                        "bmfNote1": "",
                                        "bmfLevel": "3",
                                        "bmfNote2": "",
                                        "bmfChannel": "2222",
                                        "bmfSeqno": 2,
                                        "bmfName": "存入通知存款",
                                        "bmfStt": "0",
                                        "shelfDesc": "",
                                        "bmfId": "e2a07528-5f38-48b9-9962-b754e538e828",
                                        "bmfCode": "302001070",
                                        "bmfUrl": "noticeDeposit",
                                        "bmprPrdtypecode": "",
                                        "shelfName": "",
                                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                        "bmfDesc": "",
                                        "bmprShelfcode": "",
                                        "bmfParentid": "789206f1-6db5-4dce-97c9-e9263addf209",
                                        "bmprGoodscode": "",
                                        "bmprId": ""
                                    },
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 11,
                        "bmfName": "安全管理",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "7c0ca5dc-9782-493b-987d-18e07a916ec5",
                        "bmfCode": "302001063",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "证书查询",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "f7a2bee7-5d0d-4374-a11e-3eb7f3b806a6",
                                "bmfCode": "302001071",
                                "bmfUrl": "credentialsquery",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "7c0ca5dc-9782-493b-987d-18e07a916ec5",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "证书更新",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "fbe94381-8e4d-40d3-849a-80c207f39889",
                                "bmfCode": "302001072",
                                "bmfUrl": "credentialsupdate",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "7c0ca5dc-9782-493b-987d-18e07a916ec5",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 3,
                                "bmfName": "令牌动态口令同步",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "a9d63fb8-ed50-40a6-9bb0-969e80693333",
                                "bmfCode": "302001073",
                                "bmfUrl": "dynamictoken",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "7c0ca5dc-9782-493b-987d-18e07a916ec5",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                },
                {
                    "itemValue": {
                        "bmfProperties": "N",
                        "bmprMenucode": "",
                        "parentShelf": "",
                        "bmfNote1": "",
                        "bmfLevel": "1",
                        "bmfNote2": "",
                        "bmfChannel": "2222",
                        "bmfSeqno": 12,
                        "bmfName": "客户服务",
                        "bmfStt": "0",
                        "shelfDesc": "",
                        "bmfId": "aa168fbf-432b-4186-afb1-918f3b213e62",
                        "bmfCode": "302001064",
                        "bmfUrl": "",
                        "bmprPrdtypecode": "",
                        "shelfName": "",
                        "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                        "bmfDesc": "",
                        "bmprShelfcode": "",
                        "bmfParentid": "",
                        "bmprGoodscode": "",
                        "bmprId": ""
                    },
                    "children": [
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 1,
                                "bmfName": "客户之声",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "76c8b6be-a4bd-47c8-b1d4-37c839ad1e3d",
                                "bmfCode": "302001074",
                                "bmfUrl": "customervoice",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "aa168fbf-432b-4186-afb1-918f3b213e62",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 2,
                                "bmfName": "银行客服",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "45193932-80ec-4f9f-aaf0-01f9875cccb4",
                                "bmfCode": "302001075",
                                "bmfUrl": "bankcustomer",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "aa168fbf-432b-4186-afb1-918f3b213e62",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 3,
                                "bmfName": "安全提示",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "4071f074-dd36-4c04-ad50-bfa0f73dc8f5",
                                "bmfCode": "302001076",
                                "bmfUrl": "safetytips",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "aa168fbf-432b-4186-afb1-918f3b213e62",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 4,
                                "bmfName": "银行公告",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "d09d8ae8-7cdb-428f-bad1-4381e2013178",
                                "bmfCode": "302001077",
                                "bmfUrl": "bankannouncement",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "aa168fbf-432b-4186-afb1-918f3b213e62",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        },
                        {
                            "itemValue": {
                                "bmfProperties": "N",
                                "bmprMenucode": "",
                                "parentShelf": "",
                                "bmfNote1": "",
                                "bmfLevel": "2",
                                "bmfNote2": "",
                                "bmfChannel": "2222",
                                "bmfSeqno": 5,
                                "bmfName": "短信通知管理",
                                "bmfStt": "0",
                                "shelfDesc": "",
                                "bmfId": "93ddec3e-559a-4a11-852d-2007a9ba5989",
                                "bmfCode": "302001078",
                                "bmfUrl": "smsnotification",
                                "bmprPrdtypecode": "",
                                "shelfName": "",
                                "bmfLegal": "80fb68c1-fce5-440d-85a3-9c392ba1ba83",
                                "bmfDesc": "",
                                "bmprShelfcode": "",
                                "bmfParentid": "aa168fbf-432b-4186-afb1-918f3b213e62",
                                "bmprGoodscode": "",
                                "bmprId": ""
                            },
                            "children": []
                        }
                    ]
                }
            ]
        }
    }
};